### ISSUE TITLE
error in cronjob

### ISSUE THREAD

**Issue by Joppla** [06Games/Webtrees-MailSystem#10]
Hi,

I just see your message. Yesterday I installed the mailsystem module. Today I should get the first mail, but I got this error message:
```
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file

```
The cronjob is:
```
0 7 * * * /usr/local/bin/wget -O - -q "https://mydomain.info/index.php?route=%2Fmail-sys%2Fcron" > /dev/null
```

Is this error connected with your message before, or is this something else?

**Comment by 06Games** [comment]
Hi,
Thank you for opening this issue. 
It doesn't seem to me that the error is coming from the execution of the wget, but to be sure, can you execute the command manually ?
```
/usr/local/bin/wget -O - -q "https://mydomain.info/index.php?route=%2Fmail-sys%2Fcron" > /dev/null
```

**Comment by Joppla** [comment]
I presume that I should do it on the ssh connection? If yes, nothing happened, no error, but also no mail.

**Comment by Joppla** [comment]
Hi, that didn't give any result. 

I also tested if the installation can send mail, but that will.

**Comment by 06Games** [comment]
This is strange. If you connect to this URL (https://mydomain.info/index.php?route=%2Fmail-sys%2Fcron) from a browser, it doesn't work either?
Maybe also try this one, it should respond with a JSON containing information about the module: https://mydomain.info/index.php?route=%2Fmail-sys%2Fhelp

**Comment by Joppla** [comment]
That give a lot ;-), but not a mail )-:
```
Call to a member function format() on null …/modules_v4/Webtrees-MailSystem/Helpers/News.php:20
#0 …/modules_v4/Webtrees-MailSystem/RequestHandler.php(187): EvanG\Modules\MailSystem\Helpers\News->get()
#1 [internal function]: EvanG\Modules\MailSystem\RequestHandler->EvanG\Modules\MailSystem\{closure}()
#2 …/vendor/illuminate/collections/Collection.php(695): array_map()
#3 …/modules_v4/Webtrees-MailSystem/RequestHandler.php(192): Illuminate\Support\Collection->map()
#4 …/modules_v4/Webtrees-MailSystem/RequestHandler.php(153): EvanG\Modules\MailSystem\RequestHandler->api()
#5 …/modules_v4/Webtrees-MailSystem/RequestHandler.php(134): EvanG\Modules\MailSystem\RequestHandler->htmlData()
#6 …/modules_v4/Webtrees-MailSystem/RequestHandler.php(124): EvanG\Modules\MailSystem\RequestHandler->sendMail()
#7 …/modules_v4/Webtrees-MailSystem/RequestHandler.php(113): EvanG\Modules\MailSystem\RequestHandler->sendMails()
#8 …/modules_v4/Webtrees-MailSystem/RequestHandler.php(63): EvanG\Modules\MailSystem\RequestHandler->cron()
#9 …/modules_v4/Webtrees-MailSystem/RequestHandler.php(206): EvanG\Modules\MailSystem\RequestHandler->EvanG\Modules\MailSystem\{closure}()
#10 …/app/Http/Middleware/RequestHandler.php(55): EvanG\Modules\MailSystem\RequestHandler->handle()
#11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#12 …/app/Module/CheckForNewVersion.php(115): Middleland\Dispatcher->handle()
#13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#14 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#17 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#18 …/app/Http/Middleware/Router.php(152): Fisharebest\Webtrees\Webtrees::dispatch()
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#20 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#22 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#24 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#26 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle()
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#28 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#29 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#30 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#32 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#34 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#36 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#38 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#40 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#42 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#44 …/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle()
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#46 …/app/Http/Middleware/BadBotBlocker.php(277): Middleland\Dispatcher->handle()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#48 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#50 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#52 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#53 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#55 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#57 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle()
#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#59 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#60 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#61 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#62 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#63 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#64 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#65 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#66 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#67 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#68 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#69 {main}
```

**Comment by 06Games** [comment]
The good news is that it gives an error, so we can locate the problem ;)
This is a really stupid mistake I made in the code, I will be able to fix it quickly

**Comment by Joppla** [comment]
Most times it are stupid mistakes ;-) I am happy that you found it, success with repair and thanks for helping!

**Comment by 06Games** [comment]
Yes, totally.
Could you test with the latest commit: https://github.com/06Games/Webtrees-MailSystem/archive/5816dbc386146e372d3a56db9e27efe456b9cb11.zip

**Comment by Joppla** [comment]
It works! Thanks!

**Comment by Joppla** [comment]
I am sorry that I have to re-open this issue. The cronjob in the browser works correct. But the cronjob itself gave this morning still the same error by mail. See the first message in this.

**Comment by 06Games** [comment]
Hi,
What does the execution of this command return?
```bash
wget -O - -q "https://mydomain.info/index.php?route=%2Fmail-sys%2Fcron"
```

**Comment by Joppla** [comment]
I tested and got the following message:

`{"message":"Skip","today":"2022-12-10","next":"2022-12-11"}`

But I didn't got a mail.

**Comment by 06Games** [comment]
Everything is fine, as the message says, the mailing is scheduled for tomorrow. 
The error you are getting must come from your cron configuration. Check that the other tasks in your cron file are working properly.

**Comment by Joppla** [comment]
Other task work correct. 

I modified to run the cron within 2 minutes. But still get an error mail instead of suspected.
```
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file
```

**Comment by 06Games** [comment]
You receive this in an email?

**Comment by Joppla** [comment]
yes, by mail

**Comment by 06Games** [comment]
It's really weird, the module doesn't use sh at all. The sender of the email is Webtrees?

**Comment by 06Games** [comment]
Yes, for me too, maybe we need to escape the %.
I must admit that I only tested this module with the pretty url, so it is possible that it comes from there

**Comment by Joppla** [comment]
Why doesn't I got an email when I run `wget -O - -q "https://mydomain.info/index.php?route=%2Fmail-sys%2Fcron"` in the terminal, but I got the mail when I run it in the browser?

**Comment by 06Games** [comment]
> Yes, for me too, maybe we need to escape the %. I must admit that I only tested this module with the pretty url, so it is possible that it comes from there

Indeed, it would seem that a `\` should be added before the `%`. https://stackoverflow.com/a/53095846/10792036
Could you try this cron task:
```cron
0 7 * * * /usr/local/bin/wget -O - -q "https://mydomain.info/index.php?route=\%2Fmail-sys\%2Fcron" > /dev/null
```

**Comment by 06Games** [comment]
> Why doesn't I got an email when I run `wget -O - -q "https://mydomain.info/index.php?route=%2Fmail-sys%2Fcron"` in the terminal, but I got the mail when I run `https://mydomain.info/index.php?route=%2Fmail-sys%2Fcron` in the browser?

There should be no difference. What are the sending dates that are displayed at the bottom of the module configuration page?

**Comment by Joppla** [comment]
```
Information

Last mailing: 2022-12-10
Next mailing: 2022-12-11
Number of recipients: 1
```

**Comment by Joppla** [comment]
with "\%2F" nor "\/" I got an error mail now. 
Also not another mail, but that has to be with the setting that only once day a mail will be send?

**Comment by 06Games** [comment]
> ```
> Information
> 
> Last mailing: 2022-12-10
> Next mailing: 2022-12-11
> Number of recipients: 1
> ```

And if you re-request https://mydomain.info/index.php?route=%2Fmail-sys%2Fcron in your browser it sends an email again?
Normally, you should not be able to get more than one email per day.

**Comment by 06Games** [comment]
> with "%2F" nor "/" I got an error mail now. Also not another mail, but that has to be with the setting that only once day a mail will be send?

You should apparently write `\%2F` and not just `%2F` because `%` is a special character

**Comment by 06Games** [comment]
The route is not understood if it sends you the home page. So the problem has not been solved...
Could you send me the exact cron command you are using, I will try to reproduce the problem.

**Comment by Joppla** [comment]
`17 * * * * /usr/local/bin/wget -O - -q "https://wttest.planje.info/index.php?route=\/mail-sys\/Fcron"`

**Comment by 06Games** [comment]
In my tests, this cron task worked:
```bash
0 8 * * * wget -O - -q "https://localhost/index.php?route=\%2Fmail-sys\%2Fcron"
```

**Comment by Joppla** [comment]
> In my tests, this cron task worked:
> 
> ```shell
> 0 8 * * * wget -O - -q "https://localhost/index.php?route=\%2Fmail-sys\%2Fcron"
> ```

I agree.
